import os
from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_community.document_loaders import  WebBaseLoader
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.retrievers import BM25Retriever
from langchain_classic.retrievers import EnsembleRetriever
from langchain_classic.retrievers import ParentDocumentRetriever
from langchain_classic.storage import InMemoryStore
from langchain_cohere import CohereRerank
from langchain_classic.retrievers import ContextualCompressionRetriever
from langchain_community.vectorstores import Chroma


load_dotenv()

COHERE_API_KEY = os.getenv("COHERE_API_KEY")
print(COHERE_API_KEY)
